### ISSUE TITLE
Test install rules

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/fiducials#10]
Make sure that we have all the install rules that we need to actually use pre-built packages

**Comment by jim-v** [comment]
Added install rules for fiducial_slam Python scripts.  The other looked correct.

**Comment by rohbotics** [comment]
Whenever you get a change, run a `catkin_make install` and source the install/setup.bash instead of the devel/setup.bash and see if you can still run fiducials

**Comment by jim-v** [comment]
Launch files are not installed
