### ISSUE TITLE
Publish Images param isn't used

### ISSUE THREAD

**Issue by robin-read** [UbiquityRobotics/fiducials#105]
Hello,

Just scanning through your code, I see that on line 375 in aruco_detect.cpp you publish the image with the detected markers. It looks like you're not making any use of the publish_images rosparam that is read on line 401. Is this correct?

Cheers,

R.

**Comment by jim-v** [comment]
That is correct, thank you for finding and reporting that.
We should either use the parameter as documented, or remove it.
The better solution seems to be to remove the parameter and update the documentation.

**Comment by robin-read** [comment]
Hi Jim,

Alas I would opt for using the parameter as on computation constrained systems it's perhaps unnecessary to publish the images at all. Just a user's view point :)

R.

**Comment by robin-read** [comment]
Whoops, sorry for closing!
