### ISSUE TITLE
Basic Automated Tests

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/fiducials#11]
We need tests! We can start out with some basic ones.

- [x] Publish image(s) of a fiducial in frame, and make sure that the detection outputs a sane vertices.
- [x] Use existing map, publish image of fiducial, check for sane localization.
- [x] Image with two fiducials, connect them
- [x] Bag file with video of moving through a bunch of fiducials, map should make sense (Maybe not as basic)

**Comment by jim-v** [comment]
@rohbotics Is there a place I can host a large bag file?

**Comment by rohbotics** [comment]
We should look into a static host for large files, like AWS S3, but for now I think you will have to do it from google drive/dropbox

**Comment by jim-v** [comment]
The basic tests are in place.

**Comment by rohbotics** [comment]
Great, I will take a look closer look today.

**Comment by rohbotics** [comment]
Sorry for the delay, Looks good!
