### ISSUE TITLE
How to use Aurco_detect  without raspicam?

### ISSUE THREAD

**Issue by chrissunny94** [UbiquityRobotics/fiducials#136]
The topics concerned with the camera (Currently a Kinect is publishing the below topics )

`/camera
/camera/depth/camera_info
/camera/depth/image_raw
/camera/depth/points
/camera/parameter_descriptions
/camera/parameter_updates
/camera/rgb/camera_info
/camera/rgb/image_raw
/camera/rgb/image_raw/compressed
/camera/rgb/image_raw/compressed/parameter_descriptions
/camera/rgb/image_raw/compressed/parameter_updates
/camera/rgb/image_raw/compressedDepth
/camera/rgb/image_raw/compressedDepth/parameter_descriptions
/camera/rgb/image_raw/compressedDepth/parameter_updates
/camera/rgb/image_raw/imagezero
/camera/rgb/image_raw/theora
/camera/rgb/image_raw/theora/parameter_descriptions
/camera/rgb/image_raw/theora/parameter_updates
`

**Comment by chrissunny94** [comment]
I am trying to use this launch file .

https://github.com/UbiquityRobotics/magni_robot/blob/indigo-devel/magni_nav/launch/aruco.launch

Did the following modifications . 
    
    <arg name="camera" value="/camera/rgb"/>

    <arg name="image" value="image_raw"/>
   
     <arg name="transport" value="raw"/>

**Comment by rohbotics** [comment]
Hey @chrissunny94 

Something like this should work
```
<arg name="camera" value="/camera/rgb"/>
<arg name="image" value="image_raw"/>
<arg name="transport" value="raw"/>
```

**Comment by chrissunny94** [comment]
@rohbotics , Thanks man , solved it .
