### ISSUE TITLE
aruco_detect does not detect all visible marker

### ISSUE THREAD

**Issue by nihad-s** [UbiquityRobotics/fiducials#137]
Its very strange behavior where the same marker (on the wooden pole) gets detected from quite far away but once I get close and the marker/camera are still it is not getting detected even though all the marker are clearly better visible.

![aruco_detect](https://user-images.githubusercontent.com/40424708/47562443-bee93180-d91e-11e8-940e-a21c55419ed5.png)

Putting a white background (white paper) behind the marker or while moving camera or marker makes it detectable. But I am not sure what the specific cause is so I can fix it or avoid it. Which specific setup would make it most detectable, painting the pole white, increasing white boarder of the marker, changing the detector parameters?

The launch file I am using right now is:

     <arg name="camera" default="camera/color"/>
     <node pkg="aruco_detect" name="aruco_detect" type="aruco_detect">
      <param name="image_transport" value="raw"/>
      <param name="publish_images" value="true" />
      <param name="fiducial_len" value="0.19"/>
      <param name="dictionary" value="3"/>
      <param name="do_pose_estimation" value="true"/>
      <remap from="/camera" to="$(arg camera)/image_raw"/>
      <remap from="/camera_info" to="$(arg camera)/camera_info"/>
     </node>

I have also bag of the image_raw and camera_info.
https://files.fm/u/cbscbrrn

**Comment by jim-v** [comment]
The detector is looking for a wider white border around the image than you have in the undetected fiducial.  It is possible to adjust the parameters.   They can be adjusted with [dynamic reconfigure] (http://wiki.ros.org/rqt_reconfigure) so you can find parameters that work for you and then set in the configuration or launch file.

**Comment by rohbotics** [comment]
The minimum white border we recommend is slightly larger than 1 square of the marker. 

The lines in the file from `create_markers.py` represent the recommended minimum border.

**Comment by ninnom** [comment]
I see so the border was a bigger issue than I expected. I will make sure that it is at least 2 squares from now on. 

I already looked into the parameters but they are very complicated and I don't want to make it worse for some cases where it is already working very good. Any recommendation on which parameters I should try to adjust? 

Outside of that thank you very much and you can close the Issue.
