### ISSUE TITLE
Make sure cariosvg is available

### ISSUE THREAD

**Issue by jim-v** [UbiquityRobotics/fiducials#139]
```
$ rosrun aruco_detect create_markers.py 
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/aruco_detect/create_markers.py", line 8, in <module>
    import cairosvg
ImportError: No module named cairosvg
```
This could be addressed by calling `checkCmd` or with package dependencies.

**Comment by rohbotics** [comment]
This is already in there:    
```checkCmd("cairosvg-py2", "python-cairosvg")```

now that this PR is in: https://github.com/ros/rosdistro/pull/19245/ we should just add it as a rosdep, along with joblib https://github.com/ros/rosdistro/pull/19244

**Comment by jim-v** [comment]
It shoukd have the import statement for cairo in a try block, otherwise the
script exits before the checkCmd if cairo is not installed.

**Comment by juanea** [comment]
I still have this problem.

$ rosrun aruco_detect create_markers.py 
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/aruco_detect/create_markers.py", line 8, in <module>
    import cairosvg
ImportError: No module named cairosvg

What should I do?

Thanks

**Comment by anfederman** [comment]
I just ran into this now.  If you try to run by changing to python3, the script fails. So no markers for me

**Comment by jim-v** [comment]
The issue you ran into is #161.
