### ISSUE TITLE
fiducials.pdf genMarker() 3 arguments but 2 are given

### ISSUE THREAD

**Issue by juanea** [UbiquityRobotics/fiducials#146]
Traceback (most recent call last):
  File "/home/juanea/catkin_ws/src/fiducials/aruco_detect/scripts/create_markers.py", line 117, in <module>
    genMarker(i, dicno)
TypeError: genMarker() takes exactly 3 arguments (2 given)

**Comment by rohbotics** [comment]
What is the exact command that you ran that produced this error?

**Comment by juanea** [comment]
The one on the example for creating the fiducials on the ros wiki:
http://wiki.ros.org/fiducials
`rosrun aruco_detect create_markers.py 100 112 fiducials.pdf`

**Comment by rohbotics** [comment]
Thanks for reporting the bug @juanea I opened a PR that should fix it #151
