### ISSUE TITLE
CairoSVG only with Python 3

### ISSUE THREAD

**Issue by rfeistenauer** [UbiquityRobotics/fiducials#161]
When using the command to create markers:
rosrun aruco_detect create_markers.py 100 112 fiducials.pdf

i get: ImportError: No module named cairosvg

Trying to install it results in another error:
CairoSVG does not support Python 2.x anymore. Please use Python 3 or install an older version of CairoSVG.

I already used marker creation some month ago, so I gues thats a new problem.

Even switching to older versions just causes new Errors, so maybe this dependency can be switched to something else?

**Comment by jim-v** [comment]
We will look into an alternative.  It's not clear what the best solution is, since the OpenCV Python bindings are not available for Python3 with the standard ROS packages on Kinetic.

**Comment by rohbotics** [comment]
What version of ubuntu are you on where you see this error?

**Comment by rfeistenauer** [comment]
Ubuntu 16.04 with ROS kinetic

**Comment by rohbotics** [comment]
I think svglib is a good solution, it will not be as fast as CairoSVG, but nowhere near as slow as Inkscape was with its long startup times.

I'll look into it
