### ISSUE TITLE
Datasets and configuration parameters

### ISSUE THREAD

**Issue by msteinbo1337** [UbiquityRobotics/fiducials#166]
Hey,

I want to get this fiducial SLAM run with my camera. I succeed to detect some generated tags with the aruco_detect node and display them in rviz. However there are some transform errors between some frames and I'm not able to display the path of my camera, like it is done in the demonstration at "https://www.youtube.com/watch?v=Ckf1QAuTKqc" . Are there any examples how to configure the launchfiles to get this done ? In the rviz configuration there is a displaytype named "Path" subscribing to the "/plan" topic. where is this published ?

Furthermore I tried to reproduce the results from the Datasets used in the video above, but i cant get any detection. I think u were using some Apriltags, which i cant define as the dictionary parameter in the aruco_detect launchfile. Is there any solution to fix this ?

Thank you for your support

**Comment by jim-v** [comment]
Hi @msteinbo1337,

That video is not from our software!  Our software uses aruco tags.

The `/plan' topic in rviz is for [move_basic](https://github.com/UbiquityRobotics/move_basic).

**Comment by rohbotics** [comment]
Closing this because it is not related this repo.
