### ISSUE TITLE
Getting aruco detect to work with a Asus depth camera

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/fiducials#168]
I am trying to get a non Raspberry pi camera working with aruco detect.  The camera is supplying a topic /camera/rgb/image_view/compressed  but this does not get remapped to fiducial images.

I tried editing this line in the launch file:

   <remap from="/camera/compressed" 
        to="$(arg camera)/$(arg image)/$(arg transport)"/>

to "/camera/rgb/image_view/compressed"

in the launch file to no effect.

what am I missing (besides 20 additional IQ points.)

**Comment by rohbotics** [comment]
@anfederman 

A couple points:
`/fiducial_images` is an **output** of aruco_detect, it draws nice visualizations on top of the camera output.

You say "This line in the launch file" what are you referring to? Please post your _entire_ launch file, plus the output of `rostopic list`
