### ISSUE TITLE
Is there a minimum detection distance?

### ISSUE THREAD

**Issue by canberkgurel** [UbiquityRobotics/fiducials#191]
I noticed that the aruco markers are no longer detected when the camera is any closer than ~40 cm. Is this a known feature/issue? Note that when the camera is within the 10-40 cm range, the entire marker and the surrounding white border is still visible. Is there a configuration parameter that I can change? What exactly is causing this constraint?

I know that the minimum white border recommended is slightly larger than 1 square of the marker. My markers satisfy this condition as shown below.

![20190802_091459](https://user-images.githubusercontent.com/33564573/62372989-d20cdb80-b506-11e9-9064-7b2944e40c41.jpg)

I am using is the Intel RealSense R200 camera. The camera is calibrated.

**Comment by jim-v** [comment]
Hi,

I suspect the `maxMarkerPerimeterRate` parameter is the one you should change.
The parameters `aruco_detect` node uses can be dynamically configured.   You can do this by running `rosrun rqt_reconfigure rqt_reconfigure` while the node is running to find optimal values.  These values can then be set from the launch file.

Jim

**Comment by rohbotics** [comment]
Closing this due to age and lack of response. 

@canberkgurel  Feel free to re-open if you still have questions.
