### ISSUE TITLE
Aruco_detect detects multiple tags

### ISSUE THREAD

**Issue by YuHengKit** [UbiquityRobotics/fiducials#193]
Is it possible to use Aruco_detect to detect multiples tags with different IDs in a single launch file?
Is it possible also to detect two tags and obtain the center between the tags?

Thank you.

**Comment by jim-v** [comment]
Hi, yes `aruco_detect` will detect any number of tags, as long as they are in the same dictionary.
It will publish the id of tags found and their vertices in image coordinates as well as the transforms between them and the camera.

**Comment by YuHengKit** [comment]
meaning it is not possible to detect different dictionary in a single launch file right?

**Comment by jim-v** [comment]
Yes, there can only be one dictionary.

**Comment by YuHengKit** [comment]
Alright. Thank you.
