### ISSUE TITLE
fiducial_slam ignores fiducial_id 0

### ISSUE THREAD

**Issue by rcywongaa** [UbiquityRobotics/fiducials#199]
It seems fiducial markers with id 0 are actively ignored in the mapping process.  No blue line is drawn between existing markers and marker id 0, and /fiducial_map does not publish fiducial_id: 0

Replacing marker 0 with any other marker fixes the issue.

**Comment by jim-v** [comment]
Fiducial id 0 had a special meaning in the past.   In the `kinetic-devel` branch on github this meaning has been removed, so if you build from source it should work as expected.

**Comment by rcywongaa** [comment]
Thanks for the clarification!
