### ISSUE TITLE
Stuck at Aruco Detection Ready ,what to do next to start live aruco marker detection from internal camera?

### ISSUE THREAD

**Issue by ghost** [UbiquityRobotics/fiducials#211]
yugal@yugal-ThinkPad-X230:~/ws$ roslaunch aruco_detect aruco_detect.launch 
... logging to /home/yugal/.ros/log/2c4bf6e0-6488-11ea-9589-843a4b609e78/roslaunch-yugal-ThinkPad-X230-25953.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://yugal-ThinkPad-X230:45601/

SUMMARY
========

PARAMETERS
 * /aruco_detect/dictionary: 7
 * /aruco_detect/do_pose_estimation: True
 * /aruco_detect/fiducial_len: 0.14
 * /aruco_detect/fiducial_len_override: 
 * /aruco_detect/ignore_fiducials: 
 * /aruco_detect/image_transport: compressed
 * /aruco_detect/publish_images: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    aruco_detect (aruco_detect/aruco_detect)

ROS_MASTER_URI=http://localhost:11311

process[aruco_detect-1]: started with pid [25970]
[ INFO] [1584038071.076999847]: Aruco detection ready

**Comment by ghost** [comment]
I want to use my internal webcam for aruco marker detection

**Comment by nkise** [comment]
Did you fix it?

**Comment by Canbjerg** [comment]
You need a camera image publisher topic which publishes in image_compressed format. If you are using a camera which has a already released ros wrapper like intel realsense etc. you can just link the topics and use the program freely, but if you are using a webcam you need to create your own publisher,  there are examples for it online
