### ISSUE TITLE
Slam should not segfault when no fiducials are visible when initializing map

### ISSUE THREAD

**Issue by rcywongaa** [UbiquityRobotics/fiducials#212]
Offending line: https://github.com/UbiquityRobotics/fiducials/blob/18672422d6a91299c4873e5be7824a7014508986/fiducial_slam/src/map.cpp#L446

Suggest that the system continue to attempt to initialize (by simply adding a `return;` after the line)

**Comment by rohbotics** [comment]
Hey @rcywongaa,

Sorry for the delay. This sounds like a reasonable change. Can you make a PR so that we can incorporate it?

Rohan

**Comment by dorkamotorka** [comment]
This is implemented.
