### ISSUE TITLE
Incorrect Info in ROS Wiki

### ISSUE THREAD

**Issue by beingkartik** [UbiquityRobotics/fiducials#222]
In the  ROS wiki for aruco_detect (http://wiki.ros.org/aruco_detect), it says it subscribes to /camera of type sensor_msgs/Image. Actually on running the code I see it actually subscribes to /camera/compressed which is actually being remapped from /camera/image/compressed as per the launch file. It should be a simple fix. I would like to correct this, however I can't find the source for the wiki page

**Comment by rohbotics** [comment]
Hi @beingkartik if you make a ROS wiki account, you should be able to edit the page directly.
