### ISSUE TITLE
Melodic?

### ISSUE THREAD

**Issue by pitosalas** [UbiquityRobotics/fiducials#224]
Will `sudo apt-get install ros-kinetic-fiducials` work correctly on Melodic? Does anyone know?

**Comment by MoffKalast** [comment]
I think it's unlikely since there will be a package version conflict if I recall right, but it may work if you clone and compile it yourself.

**Comment by madgrizzle** [comment]
I installed it on melodic using

`sudo apt-get install ros-melodic-fiducials`

**Comment by anfederman** [comment]
Catkin_make worked in Melodic, failed in Noetic.  I think this is a OpenCV 4 version issue.

**Comment by rohbotics** [comment]
Melodic and Noetic should both be released now.
