### ISSUE TITLE
Migration to vision_msgs

### ISSUE THREAD

**Issue by dorkamotorka** [UbiquityRobotics/fiducials#234]
New standard ROS vision_msgs were released, we should consider migrating from our custom messages.

**Comment by JanezCim** [comment]
Since this will be necessary quite soon for another project in putting it in ready

**Comment by JanezCim** [comment]
So i've used fiducials with new messages and they seem to be working quire alright (they are on branch lama). We should consider making a PR for this once its well tested :)
