### ISSUE TITLE
Release aruco_detect for ROS noetic?

### ISSUE THREAD

**Issue by ajithcodesit** [UbiquityRobotics/fiducials#238]
Is it possible to release `aruco_detect` for ROS noetic?

**Comment by MoffKalast** [comment]
As in an apt package? Should be possible. Does it compile on noetic right now? The marker gen script would probably need to be updated to python 3 I suppose.

In general we'll be going over all of our repositories and making noetic versions very soon.

**Comment by ajithcodesit** [comment]
@MoffKalast  Yes as an apt package. I am able to compile the package in noetic but have not tested it. I was able to fix the marker generator script for python 3.

**Comment by rohbotics** [comment]
@ajithcodesit If you could make a PR with any noetic required changes once you have tested that everything works that would be appreciated!

**Comment by anfederman** [comment]
I noticed in aruco_gazebo there was a call to python2 in the !#
I think it made on the RPI4 both ARM32 and ARM64, also on my ubuntu 18,04/melodic laptop.

I just tried a catkin_make on AMD64 20.04 Noetic, make fails on aruco_detect.cpp on line 430,58. the error is about no matching function call to 'FiducialsNode::estimatePose ....
   ...
430 |

**Comment by anfederman** [comment]
430  --- reprojectionerror);
                                       ^

**Comment by anfederman** [comment]
This might be due to a cv2 version issue on line 222 it says candidate expects 6 arguments, 8 provided.
