### ISSUE TITLE
Aruco_detect.cpp make fails in Noetic

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/fiducials#242]
I compiled OK in Melodic with python2, opencv 3.3

It failed in catkin_make with python3, opencv 4.  

I think the same issue is in other fiducials nodes.  the function has a different number of variables in different versions of opencv,

**Comment by rohbotics** [comment]
Can you post the exact error in here Alan? Thanks

**Comment by anfederman** [comment]
This now works, I don't recall what the issue was or what I did to fix it, was probably a typo when I was looking at the code.  Aruco detect works, and fiducial_slam is showing markers in rviz in the correct locations, but I haven't tried building a map or navigating the robot based on fiducial_slam.

fiducial_follow is not working yet, I raised an issue in magni_demos.

**Comment by not-vibhu** [comment]
Hi @anfederman 
Were you able to build this in Noetic?

**Comment by igor-markovic** [comment]
I can confirm that the code from the kinetic-devel branch builds fine on a fresh install on Ubuntu 20.04 with ros-noetic-desktop-full installed, OpenCV version 4.2.

**Comment by rohbotics** [comment]
Closing because the noetic-devel branch builds under noetic.
