### ISSUE TITLE
How can aruco-boards be detected with this package?

### ISSUE THREAD

**Issue by fmros** [UbiquityRobotics/fiducials#245]

**Comment by JanezCim** [comment]
The instructions of how to use these packages can be found on http://wiki.ros.org/fiducials. Or do you have more specific questions?

**Comment by fmros** [comment]
> The instructions of how to use these packages can be found on http://wiki.ros.org/fiducials. Or do you have more specific questions?

I wanted to try  to increase detection accuracy by using marker-boards(see this [link](https://stackoverflow.com/a/51736875)). So my question is, is it possible to detect a marker-board or aruco-board with this package?

See also here: https://docs.opencv.org/master/db/da9/tutorial_aruco_board_detection.html

**Comment by caioaamaral** [comment]
> > The instructions of how to use these packages can be found on http://wiki.ros.org/fiducials. Or do you have more specific questions?
> 
> I wanted to try to increase detection accuracy by using marker-boards(see this [link](https://stackoverflow.com/a/51736875)). So my question is, is it possible to detect a marker-board or aruco-board with this package?
> 
> See also here: https://docs.opencv.org/master/db/da9/tutorial_aruco_board_detection.html

Aruco detector will detect each tag displayed on your aruco board. If you're interested in a specific position, you will need to reference it (as a static tf for example) to the position of each tag (the detected position of course) and then use some sort of filter (kalman filter from robot_localization is a good example) to retrieve the optimal position estimation

**Comment by fmros** [comment]
> > > The instructions of how to use these packages can be found on http://wiki.ros.org/fiducials. Or do you have more specific questions?
> > 
> > 
> > I wanted to try to increase detection accuracy by using marker-boards(see this [link](https://stackoverflow.com/a/51736875)). So my question is, is it possible to detect a marker-board or aruco-board with this package?
> > See also here: https://docs.opencv.org/master/db/da9/tutorial_aruco_board_detection.html
> 
> Aruco detector will detect each tag displayed on your aruco board. If you're interested in a specific position, you will need to reference it (as a static tf for example) to the position of each tag (the detected position of course) and then use some sort of filter (kalman filter from robot_localization is a good example) to retrieve the optimal position estimation


So If i would want to get one position out of a board of 4 markers, I have to deal with the 4 detected fiducial frames of this package, and combine them to a group estimate with other techniques. Is this what you intend?

**Comment by JanezCim** [comment]
> Aruco detector will detect each tag displayed on your aruco board. If you're interested in a specific position, you will need to reference it (as a static tf for example) to the position of each tag (the detected position of course) and then use some sort of filter (kalman filter from robot_localization is a good example) to retrieve the optimal position estimation

I would agree with that

> So If i would want to get one position out of a board of 4 markers, I have to deal with the 4 detected fiducial frames of this package, and combine them to a group estimate with other techniques. Is this what you intend?

yep

**Comment by fmros** [comment]
Thank you!
