### ISSUE TITLE
Open ROS2 branch for port

### ISSUE THREAD

**Issue by agutenkunst** [UbiquityRobotics/fiducials#247]
Hi!

I did some work on porting this to ROS2 foxy see https://github.com/agutenkunst/fiducials/tree/ros2
there are still some things to do however I figured opening a draft PR is a good start for technical discussions and getting support.

In order to open the PR I need a target branch. Not sure if "ros2" or "foxy-devel" is the best.

What do you think?

**Comment by rohbotics** [comment]
That would be great! Opened a foxy-devel: https://github.com/UbiquityRobotics/fiducials/tree/foxy-devel, go ahead and make a draft PR to it.

Thanks!
