### ISSUE TITLE
Detected 0 markers

### ISSUE THREAD

**Issue by koliber31** [UbiquityRobotics/fiducials#272]
I'm trying to use aruco_detect by using 
`rosrun aruco_detect aruco_detect /camera:=/usb_cam/image_raw /camera_info:=/usb_cam/camera_info _publish_images:=true`.
1. I'm not sure if using /camera instead of /camera/compressed is good thing but when i was using /camera/compressed i haven't seen this topic between camera and aruco.
2. When i'm using above command to run aruco_node i get information "Detected 0 markers" although i'm holding marker in front of camera.

**Comment by anfederman** [comment]
What does rostopic list show? There should be fiducial topics and rostopic
echo should show data. If not, there is probably a transform missing or a
topic misnamed. Also is fiducial_slam is being used, the camera position
relative to the robot and camera needs to be accounted for.

**Comment by koliber31** [comment]
rostopic list
`/aruco_detect/parameter_descriptions
/aruco_detect/parameter_updates
/clicked_point
/fiducial_images
/fiducial_images/compressed
/fiducial_images/compressed/parameter_descriptions
/fiducial_images/compressed/parameter_updates
/fiducial_images/compressedDepth
/fiducial_images/compressedDepth/parameter_descriptions
/fiducial_images/compressedDepth/parameter_updates
/fiducial_images/theora
/fiducial_images/theora/parameter_descriptions
/fiducial_images/theora/parameter_updates
/fiducial_transforms
/fiducial_vertices
/initialpose
/move_base_simple/goal
/rosout
/rosout_agg
/tf
/tf_static
/usb_cam/camera_info
/usb_cam/image_raw
/usb_cam/image_raw/compressed
/usb_cam/image_raw/compressed/parameter_descriptions
/usb_cam/image_raw/compressed/parameter_updates
/usb_cam/image_raw/compressedDepth
/usb_cam/image_raw/compressedDepth/parameter_descriptions
/usb_cam/image_raw/compressedDepth/parameter_updates
/usb_cam/image_raw/theora
/usb_cam/image_raw/theora/parameter_descriptions
/usb_cam/image_raw/theora/parameter_updates
`
rostopic echo /fiducial_transforms
`header: 
  seq: 3510
  stamp: 
    secs: 1653928621
    nsecs: 232605798
  frame_id: "head_camera"
image_seq: 3510
transforms: []
`
rostopic echo /fiducial_vertices
`
header: 
  seq: 6038
  stamp: 
    secs: 1653928705
    nsecs: 498679778
  frame_id: "head_camera"
image_seq: 6038
fiducials: []
`
Messages that i get from using aruco_detect
`[ INFO] [1653929175.500986007]: Got image 20138
[ INFO] [1653929175.512547677]: Detected 0 markers
[ INFO] [1653929175.533858802]: Got image 20139
[ INFO] [1653929175.547884351]: Detected 0 markers
`

![rosgraph](https://user-images.githubusercontent.com/42122590/171033616-379b174e-ed1b-488f-b2aa-7537d516315e.png)


![aruco](https://user-images.githubusercontent.com/42122590/171033532-cc372095-b52d-463c-b970-447822587077.png)

I'm not using fiducial_slam yet, I want to detect aruco markers properly first.

**Comment by anfederman** [comment]
Hard do see what the warning is in rviz, but my guess is there is no
transform between the fiducial location(vertices) and the map, so rviz
can't locate the the vertices on the map.  You might want to look at our
github code  fro magni_gazebo fiducial_world.launch and see how we do it.
I also seem to remember you need to calibrate the usb_cam .

**Comment by anfederman** [comment]
aruco.launch:


<launch>
  <arg name="mapping_mode" default="false"/>
  <arg name="fiducial_len" default="0.140"/>

  
  <include file="$(find
raspicam_node)/launch/camerav2_1280x960_10fps.launch" />

  
  <include file="$(find aruco_detect)/launch/aruco_detect.launch">
    <arg name="camera" value="/raspicam_node"/>
    <arg name="image" value="image"/>
    <arg name="transport" value="compressed"/>

    
    <arg name="fiducial_len" value="$(arg fiducial_len)" />
  </include>

  
  <include file="$(find fiducial_slam)/launch/fiducial_slam.launch">
    <arg name="map_frame" value="map"/>
    <arg name="odom_frame" value="odom"/>
    <arg name="base_frame" value="base_footprint"/>
    <arg name="future_date_transforms" value="0.5"/>
  </include>
</launch>

you need to specify the 'frames' for rviz to work,

**Comment by koliber31** [comment]
I found out what the problem was. It turned out that i was using aruco markers from wrong dictionary. It is kinda weird because i was changing dictionary  parameters but it seems like you have to use specific markers which are in fiducials on ros wiki.
