### ISSUE TITLE
Reset map service for fiducial_slam

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/fiducials#35]
It would be useful to enable better testing.

**Comment by jim-v** [comment]
Would this clear the map and reload the initial map?

**Comment by rohbotics** [comment]
I think providing the initial map over the service call would be the best strategy.

**Comment by jim-v** [comment]
This needs to be re-implemented in the C++ version of fiducial_slam.

**Comment by rohbotics** [comment]
For clarity, since this issue has some old stuff in it too, with the map auto-initialization stuff we have now, this needs to simply clear out the old map.
