### ISSUE TITLE
Remove stuff from fiducial_detect that fiducial_slam does

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/fiducials#40]
Get rid of the marker publishing

**Comment by jim-v** [comment]
all the tf related code can come out too.

**Comment by rohbotics** [comment]
Should I remove the estimate_pose parameter, as we will always need to publish the transforms?

**Comment by jim-v** [comment]
We could leave the estimate_pose parameter in defaulted to false, in case anyone wanted to use a different pose estimator

**Comment by rohbotics** [comment]
Ok
