### ISSUE TITLE
aruco_detect should publish empty fiducial_vertices

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/fiducials#47]
When there are no markers, we should publish an empty fiducial_vertices

**Comment by jim-v** [comment]
Yes, I agree.  What do you think about having a single Fiducial message containing both vertices and transforms?  It would fix an inconsistency that there is one message for each set of vertices, but all the transforms for a frame are published together.

**Comment by rohbotics** [comment]
I think we could refactor the messages to be more consistent. But I think that we should keep them separate in order to allow making the detection and pose estimation into separate nodelets in the future.
