### ISSUE TITLE
Marker lateral drift

### ISSUE THREAD

**Issue by sevenbitbyte** [UbiquityRobotics/fiducials#74]
Very minor errors in marker angular pose estimates cause large lateral jumps in the `/map` frame. The 3DoF position data is great while the full 6DoF pose is extremely noisy.

![latteral-shifts](https://cloud.githubusercontent.com/assets/662932/25960864/24c44c38-362d-11e7-9ff8-5844c58ba7bd.gif)

In this below case I'm not sure why the tf and markers are soo far away in both X & Y lateral directions while Z looks good:

![screenshot from 2017-05-10 15-24-10](https://cloud.githubusercontent.com/assets/662932/25961355/e572230a-362e-11e7-8e8d-185a521ddb71.png)

**Comment by rohbotics** [comment]
Closing due to staleness
