### ISSUE TITLE
Build Error in fiducial_pose, Fiducial.h is missing

### ISSUE THREAD

**Issue by maxpolzin** [UbiquityRobotics/fiducials#76]
I get the following error, when I compile the package with catkin_make:

fatal error: fiducial_msgs/Fiducial.h: No such file or directory

This can be fixed by inserting

add_dependencies(rpp_pose ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})

in fiducial_pose/CMakeList.txt

I am on Ubuntu 16.04, Opencv 3.2.0, ROS Kinetic

**Comment by rohbotics** [comment]
Thanks for reporting this issue. 

Since you already have a solution, can you please create a Pull Request to contribute this change.

**Comment by ROSDevoloper** [comment]
i used this  ` sudo apt-get install ros-kinetic-aruco-detect` to install the needed dependencies required for rr_auto_dock pkg
