### ISSUE TITLE
Question about fiducial_pose topic

### ISSUE THREAD

**Issue by nav-go** [UbiquityRobotics/fiducials#96]
Is the fiducial_pose topic supposed to have its frame_id as "camera"? As I understand it, the pose being published is wrt the specified map_frame, correct? 

```
posePub.publish(toPose(basePose));

    tf2::Stamped<TransformWithVariance> outPose = basePose;
    outPose.frame_id_ = mapFrame;
    string outFrame=baseFrame;
```
The code above in map.cpp shows it being set to map frame, but echoing the topic shows frame_id to be camera. Am I missing something here?

This issue causes problems when using this topic in other packages.

**Comment by jimvaughan** [comment]
The frame_id in the fiducial_pose message is the same as the frame_id in the image from which the pose was determined.  It should be a frame for which a tf exists, so that fiducial_slam can lookup the tf to determine the camera's pose wrt to the robot.  After the pose of the camera is determined by SLAM, the pose of the robot is determined with the camera to robot tf.  If you want to change the image frame_id, you should look at the camera's configuration.

Can you elaborate on what problems you have when using this topic?

**Comment by jimvaughan** [comment]
I'm sorry, I made a mistake.  I thought you were referring to the fiducial_transform messages, which should have the camera's frame_id.  The fiducial_pose messages should be in the map frame.  It looks like the mapFrame variable is set to "camera", is that correct?  Can you check the setting of map_frame with `rosparam`

**Comment by nav-go** [comment]
rosparam shows /fiducial_slam/map_frame to be map, but the frame_id of fiducial_pose is still "camera".

**Comment by jimvaughan** [comment]
Yes, you're right: the frame_id of basePose should be set to mapFrame.   Just curious, what are you using the fiducial_pose topic for, are you doing sensor fusion?

**Comment by nav-go** [comment]
Yes, I'm trying to use it with the robot_localisation package for sensor fusion.

**Comment by nav-go** [comment]
Where do you think it is getting set to 'camera', and how can we modify it?

**Comment by jimvaughan** [comment]
It's set to camera because the camera pose was one of the tfs used to generate it.

Just above `posePub.publish(toPose(basePose));`
it should have `basePose.frame_id_ = mapFrame;`

Do you mind making that change and submitting a PR?

**Comment by nav-go** [comment]
Checked the fix (works!) and submitted a PR from my old fork of fiducials. I hope it can be merged with your newer fork (I'm new to making PRs).

**Comment by jimvaughan** [comment]
Thanks for finding and reporting the bug!

**Comment by rohbotics** [comment]
The fix is merged so I am closing this.
